services:
    # event listeners
    phlexible_element_task.listener.task:
        class: Phlexible\Bundle\ElementTaskBundle\EventListener\TaskListener
        arguments:
            - "@phlexible_task.task_manager"
            - "@security.token_storage"
        tags:
            - {name: kernel.event_subscriber}

    phlexible_element_task.listener.load_data:
        class: Phlexible\Bundle\ElementTaskBundle\EventListener\LoadDataListener
        arguments:
            - "@phlexible_task.task_manager"
            - "@phlexible_user.user_manager"
            - "@security.token_storage"
        tags:
            - {name: kernel.event_listener, event: phlexible_element.load_data, method: onLoadData}

    # role providers
    phlexible_element_task.role_provider:
        class: Phlexible\Bundle\ElementTaskBundle\RoleProvider\ElementTaskRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
