services:
    # event listeners
    phlexible_element_task.listener.task:
        class: Phlexible\Bundle\ElementTaskBundle\EventListener\TaskListener
        arguments:
            - "@phlexible_task.task_manager"
            - "@security.token_storage"
        tags:
            - {name: kernel.event_subscriber}
